### ISSUE TITLE
OrcaFlex | Refactor postprocess code

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/digitalmodel#61]
-  Robust warnings for postprocess
  - [ ] dynamic analysis raise when processing partial (i.e. 
    - [ ] 0 to 600s vs. 0 to 10s small portion warning
    - [ ] LatestWave vs. 0 to 300s  small portion warning, regular wave vs. random wave
-  Develop following capabilities.
  - [ ] RangeGraph (csv) - Code required
  - [ ] Add regular wave and random wave files
  - [ ] Add umbilical with contact analysis file (Add historical umbilical analysis file)
-  Write comprehensive test (for summary and timetraces) before touching code.
  - [x] Summary (csv) (@getsivakumar, WE 11/22)
    - [x] (12/10) Updates to post processing code
  - [x] TimeHistory (csv)  (@getsivakumar, WE 11/22)
-  OrcaFlex model building
  - [x] flow diagram.  [model_building](https://github.com/vamseeachanta/digitalmodel/blob/202409/docs/pkg_orcaflex/notes/pre_model/pre_model_dynamics.png) (@getsivakumar  WE 12/06)  
  - [ ] prepare code to read coeffs from .csv files
- Orcaflex postprocess code improvements
  -  [x] Add plantuml workflow to document process. [orcaflex_post_process.png](https://github.com/vamseeachanta/digitalmodel/blob/a0702f60efe5e5d627b2830876a257b486147aef/docs/pkg_orcaflex/notes/post_general/orcaflex_post_process.png) (@getsivakumar  WE 11/29)
  -  [x] Add master settings to consolidate repeat commands 
  -  [x] Consolidate file management (from assetutilities)
  - [x] Summary (csv)   (@getsivakumar, WE 11/22)
  - [x] linkedstatistics generic code #72 (@getsivakumar week of 12/06)
  - [x] TimeHistory (csv)   (@getsivakumar, WE 11/22)
  - [ ] RangeGraph (csv)
  -  [ ] OrcaFlex visualizations
- Load model file one by one and finish all postprocessing analysis
  - [x] Summary (csv). 
  - [x] linkedstatistics #72 (@getsivakumar week of 12/06)
  - [x] TimeHistory (csv)
  - [x] RangeGraph (csv)
  - [x] OrcaFlex visualization
-  [ ] Make OrcaFlex postprocess a parallel process (TBA)
- WLNG Project code
  - [x] initial cut post processing enhancements to support FSTs and LWL (@getsivakumar WE 11/29)
  - [x] initial cut post processing for fatigue (@getsivakumar  WE 11/29)
  - [x] clean up and close out FSTs and LWL post processing files (@getsivakumar  WE 11/29)
  - [x] FST timetrace outputs #71 (@getsivakumar week of 12/06)
  - [x] FST linkedstatistics outputs #72 (@getsivakumar week of 12/06)

**Comment by getsivakumar** [comment]
Hmm these are input files handled by your Python code ? 

I ran into the same thing. Addressed this in ace engineer consultation things somewhere. Have to look.

**Comment by getsivakumar** [comment]
hi @vamseeachanta completed minor updates to post processing updates.
